language: java
jdk:
- openjdk8


services:
  - docker

before_script :
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

addons :
  mariadb : '10.0'

before_install :

- mysql -e 'CREATE DATABASE demo_maven;'
